image: node:8.9.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  
  # cli
  - npm install hexo-cli -g
  # sitemap
  # - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save

  # deploy
  - hexo deploy

  # robots
  - cp robots.txt public

  artifacts:
    paths:
    - public
  only:
  - master
