image: node:8.10.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  
  # install cli
  - npm install -g hexo-cli
  
  # update dependencies
  - npm install

  # deploy
  - hexo deploy

  # robots
  - cp robots.txt public

  artifacts:
    paths:
    - public
  only:
  - master
