image: node:6.11.5

pages:
  cache:
    paths:
    - node_modules/

  script:
  
  - npm install hexo-cli -g
  # RSS
  - npm install hexo-generator-feed --save
  # 搜索
  - npm install hexo-generator-searchdb --save
  # api
  - npm install hexo-generator-restful --save
  # sitemap
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-baidu-sitemap --save

  - hexo deploy

  # robots
  - cp robots.txt public

  artifacts:
    paths:
    - public
  only:
  - master
