image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  
  # install cli
  - yarn global add hexo-cli
  
  # update dependencies
  - yarn install

  # generate
  - hexo generate

  # robots
  - cp robots.txt public

  environment:
    name: page
    url: https://jiangtj.gitlab.io

  artifacts:
    paths:
    - public
  only:
  - master
