image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-renderer-less --save
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-json-content --save
  - npm install
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
