dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]

pages:
  image: node:8.11.2
  cache:
    paths:
    - node_modules/

  script:
  
  # install cli
  - yarn global add hexo-cli
  
  # update dependencies
  - yarn install

  # generate
  - hexo generate

  # robots
  - cp robots.txt public

  environment:
    name: page

  artifacts:
    paths:
    - public
  only:
  - master
