image: node:6.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  # RSS
  - npm install hexo-generator-feed --save
  # 搜索
  - npm install hexo-generator-searchdb --save
  # api
  - npm install hexo-generator-restful --save
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
