image: node:8.9.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  
  # install cli
  - npm install hexo-cli -g
  
  # update dependencies
  - npm install

  # deploy
  - hexo deploy

  # robots
  - cp robots.txt public

  artifacts:
    paths:
    - public
  only:
  - master
